defmodule Volley.Repo.Migrations.AddFinishedAndDeleteEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:scoring_matches) do
      add :finished?, :boolean
    end

    drop constraint(:scoring_events, "scoring_events_match_id_fkey")

    alter table(:scoring_events) do
      modify :match_id,
             references(:scoring_matches,
               column: :id,
               name: "scoring_events_match_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:scoring_events, "scoring_events_match_id_fkey")

    alter table(:scoring_events) do
      modify :match_id,
             references(:scoring_matches,
               column: :id,
               name: "scoring_events_match_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:scoring_matches) do
      remove :finished?
    end
  end
end
