defmodule Volley.Repo.Migrations.AddSetsAndSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:scoring_matches) do
      remove :b_name
      remove :a_name
      add :a_sets, :bigint, default: 0
      add :b_sets, :bigint, default: 0
      add :settings, :map, null: false
    end
  end

  def down do
    alter table(:scoring_matches) do
      remove :settings
      remove :b_sets
      remove :a_sets
      add :a_name, :text, null: false, default: "Team A"
      add :b_name, :text, null: false, default: "Team B"
    end
  end
end
