defmodule Volley.Repo.Migrations.AddMatchOwnership do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:scoring_matches) do
      add :owner_id, :bigint
      add :anonymous_owner_id, :text
    end
  end

  def down do
    alter table(:scoring_matches) do
      remove :anonymous_owner_id
      remove :owner_id
    end
  end
end
